version: '3'
services:
  ratisexe-api:
    build: 
      context: .
      dockerfile: Dockerfile 
    image: prisma_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma